spring:
  application:
    name: open-bank
  reactor:
    context-propagation: auto

app:
  r2dbc:
    url: ${OPEN_BANK_R2DBC_URL:r2dbc:postgresql://localhost:5432/api_test?schema=openbank}
    username: ${OPEN_BANK_DB_USERNAME:api_test}
    password: ${OPEN_BANK_DB_PASSWORD:api_test}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
  tracing:
    baggage:
      remote-fields: op-trace-id,op-parent-span-id,client-id,op-channel,op-span-id
      correlation:
        fields: trace_id,parent_span_id,clientId
    propagation:
      type: w3c

tracing-interceptor:
  enabled: true

server:
  port: ${PORT:8080}
